# Generated by Django 3.2.5 on 2021-12-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Treasury', '0002_bankaccount_hometreasury'),
        ('Machines', '0004_machinesorderoperations'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinesorderoperations',
            name='treasury_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Treasury.worktreasury', verbose_name='الخزنة المستخدمة'),
        ),
    ]
