# Generated by Django 3.2.5 on 2021-12-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0005_machinesorderoperations_treasury_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinesorderoperations',
            name='warehouse_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Machines.machineswarehouses', verbose_name='المخزن المستخدم'),
        ),
    ]
