# Generated by Django 3.2.5 on 2021-12-15 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0006_machinesorderoperations_warehouse_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0, verbose_name='الكمية')),
                ('purchase_cost', models.FloatField(default=0.0, verbose_name='سعر الشراء')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machines.machinesnames', verbose_name='المنتج')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machines.machineswarehouses', verbose_name='المخزن')),
            ],
        ),
    ]
