# Generated by Django 3.2.5 on 2021-12-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0008_alter_machinesorderoperations_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinesorderoperations',
            name='operation_type',
            field=models.IntegerField(choices=[(1, 'دفع عربون'), (2, 'دفع باقي المبلغ'), (3, 'دفع مبلغ تخليص البضاعة'), (4, 'استلام البضاعة')], default=0, verbose_name='نوع العملية'),
        ),
    ]
