# Generated by Django 3.2.5 on 2021-12-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0009_alter_machinesorderoperations_operation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinessuppliers',
            name='credit_or_debit',
        ),
        migrations.RemoveField(
            model_name='machinessuppliers',
            name='initial_balance',
        ),
    ]
