# Generated by Django 3.2.5 on 2021-12-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0011_machinesnames_machine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinesorderoperations',
            name='operation_date',
            field=models.DateTimeField(null=True, verbose_name='تاريخ العملية'),
        ),
        migrations.AlterField(
            model_name='machinesorderoperations',
            name='operation_type',
            field=models.IntegerField(choices=[(1, 'دفع عربون'), (2, 'دفع باقي المبلغ'), (3, 'دفع مبلغ تخليص البضاعة'), (4, 'استلام البضاعة'), (5, 'دفع الضرائب')], default=0, verbose_name='نوع العملية'),
        ),
    ]
