# Generated by Django 3.2.5 on 2021-12-22 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpareParts', '0017_auto_20211221_2202'),
        ('Machines', '0012_auto_20211221_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='تاريخ الصيانة')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machines.machineswarehouses', verbose_name='المكينة')),
                ('spareparts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpareParts.sparepartsnames', verbose_name='قطعة الغيار')),
            ],
        ),
    ]
