# Generated by Django 3.2.5 on 2021-12-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0014_auto_20211223_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='cost',
            field=models.FloatField(default=0.0, verbose_name='التكلفة'),
        ),
    ]
