# Generated by Django 3.2.5 on 2021-12-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0015_maintenance_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(null=True, verbose_name='تاريخ الصيانة'),
        ),
    ]
