# Generated by Django 3.2.5 on 2021-12-25 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0016_alter_maintenance_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
