# Generated by Django 3.2.5 on 2022-01-01 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0017_delete_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineNotifecation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(null=True, verbose_name='تاريخ الانشاء')),
                ('notifeaction_type', models.IntegerField(choices=[(1, 'موعد دفع العربون'), (2, 'موعد دفع باقي المبلغ'), (3, 'موعد تخليص البضاعة'), (4, 'موعد استلام البضاعة'), (5, 'موعد دفع الضرائب')], default=0, verbose_name='نوع الاشعار')),
                ('message', models.CharField(max_length=50, null=True, verbose_name=' الرسالة')),
                ('read', models.BooleanField(default=0, verbose_name='قرأت / لم تقرأ')),
                ('machine_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Machines.machinesorders', verbose_name='الطلبية')),
            ],
        ),
    ]
