# Generated by Django 3.2.5 on 2022-01-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0018_machinenotifecation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinenotifecation',
            name='message',
            field=models.CharField(max_length=100, null=True, verbose_name=' الرسالة'),
        ),
    ]
