# Generated by Django 3.2.5 on 2022-01-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0019_alter_machinenotifecation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinenotifecation',
            name='notifeaction_type',
            field=models.IntegerField(choices=[(1, 'موعد دفع العربون'), (2, 'موعد دفع باقي المبلغ'), (3, 'موعد استلام البضاعة'), (4, 'موعد دفع الضرائب')], default=0, verbose_name='نوع الاشعار'),
        ),
        migrations.AlterField(
            model_name='machinesorders',
            name='order_date',
            field=models.DateField(null=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='machinesorders',
            name='order_deposit_date',
            field=models.DateField(null=True, verbose_name='تاريخ دفع العربون'),
        ),
        migrations.AlterField(
            model_name='machinesorders',
            name='order_receipt_date',
            field=models.DateField(null=True, verbose_name='تاريخ استلام البضاعة'),
        ),
        migrations.AlterField(
            model_name='machinesorders',
            name='order_rest_date',
            field=models.DateField(null=True, verbose_name='تاريخ دفع باقي المبلغ'),
        ),
    ]
