# Generated by Django 3.2.5 on 2022-01-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0021_auto_20220106_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinenotifecation',
            name='notifeaction_type',
            field=models.IntegerField(choices=[(1, 'موعد دفع عربون مكينة'), (2, 'موعد دفع باقي مبلغ مكينة'), (3, 'موعد استلام بضاعة مكينة'), (4, 'موعد دفع ضرائب مكينة'), (5, 'موعد دفع عربون قطع غيار'), (6, 'موعد دفع باقي مبلغ قطع غيار'), (7, 'موعد استلام بضاعة قطع غيار'), (8, 'موعد ضرائب قطع غيار')], default=0, verbose_name='نوع الاشعار'),
        ),
    ]
