# Generated by Django 3.2.5 on 2022-02-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_systeminformation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='worker_active',
            field=models.BooleanField(default=True, verbose_name='تنشيط مخازن العمال '),
        ),
    ]
