# Generated by Django 3.2.5 on 2021-12-05 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpareParts', '0002_sparepartssuppliers_credit_or_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartsorderproducts',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SpareParts.sparepartsnames', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='sparepartsorders',
            name='order_date',
            field=models.DateField(null=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='sparepartsorders',
            name='order_deposit_date',
            field=models.DateField(null=True, verbose_name='تاريخ دفع العربون'),
        ),
        migrations.AlterField(
            model_name='sparepartsorders',
            name='order_receipt_date',
            field=models.DateField(null=True, verbose_name='تاريخ استلام البضاعة'),
        ),
        migrations.AlterField(
            model_name='sparepartsorders',
            name='order_rest_date',
            field=models.DateField(null=True, verbose_name='تاريخ دفع باقي المبلغ'),
        ),
    ]
