# Generated by Django 3.2.5 on 2021-12-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpareParts', '0003_auto_20211205_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepartssuppliers',
            name='initial_balance',
        ),
    ]
