# Generated by Django 3.2.5 on 2021-12-10 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpareParts', '0004_remove_sparepartssuppliers_initial_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartsOrderOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('operation_type', models.IntegerField(choices=[(1, 'دفع عربون'), (2, 'دفع باقي المبلغ'), (3, 'استلام البضاعة')], default=0, verbose_name='نوع العملية')),
                ('operation_value', models.FloatField(default=0, verbose_name='قيمة العملية')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpareParts.sparepartsorders', verbose_name='رقم الطلب')),
            ],
        ),
    ]
