# Generated by Django 3.2.5 on 2021-12-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpareParts', '0005_sparepartsorderoperations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartsorderoperations',
            name='operation_type',
            field=models.IntegerField(choices=[('1', 'دفع عربون'), ('2', 'دفع باقي المبلغ'), ('3', 'استلام البضاعة')], default=0, verbose_name='نوع العملية'),
        ),
    ]
