# Generated by Django 3.2.5 on 2021-12-16 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Treasury', '0006_auto_20211214_1623'),
        ('SpareParts', '0007_alter_sparepartsorderoperations_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartsorderoperations',
            name='treasury_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Treasury.worktreasury', verbose_name='الخزينة المستخدم'),
        ),
        migrations.AddField(
            model_name='sparepartsorderoperations',
            name='warehouse_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='SpareParts.sparepartswarehouses', verbose_name='المخزن المستخدم'),
        ),
        migrations.AlterField(
            model_name='sparepartsorderoperations',
            name='operation_type',
            field=models.IntegerField(choices=[(1, 'دفع عربون'), (2, 'دفع باقي المبلغ'), (3, 'استلام البضاعة'), (4, 'دفع مبلغ تخليص البضاعة')], default=0, verbose_name='نوع العملية'),
        ),
    ]
