# Generated by Django 3.2.5 on 2021-12-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpareParts', '0010_auto_20211216_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartsorderoperations',
            name='operation_type',
            field=models.IntegerField(choices=[(1, 'دفع عربون'), (2, 'دفع باقي المبلغ'), (3, 'دفع مبلغ تخليص البضاعة'), (4, 'استلام البضاعة')], default=0, verbose_name='نوع العملية'),
        ),
    ]
