# Generated by Django 3.2.5 on 2021-12-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Treasury', '0006_auto_20211214_1623'),
        ('SpareParts', '0011_alter_sparepartsorderoperations_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartsorderoperations',
            name='treasury_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Treasury.worktreasury', verbose_name='الخزينة المستخدم'),
        ),
        migrations.AlterField(
            model_name='sparepartsorderoperations',
            name='warehouse_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SpareParts.sparepartswarehouses', verbose_name='المخزن المستخدم'),
        ),
        migrations.AlterField(
            model_name='sparepartswarehousetransactions',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SpareParts.sparepartsnames', verbose_name='المنتجات'),
        ),
        migrations.AlterField(
            model_name='sparepartswarehousetransactions',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SpareParts.sparepartswarehouses', verbose_name='المخزن'),
        ),
    ]
