# Generated by Django 3.2.5 on 2021-12-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpareParts', '0013_sparepartssuppliers_initial_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepartssuppliers',
            name='credit_or_debit',
        ),
        migrations.RemoveField(
            model_name='sparepartssuppliers',
            name='initial_balance',
        ),
    ]
