# Generated by Django 3.2.5 on 2021-12-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treasury', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('account_no', models.CharField(blank=True, max_length=128, null=True, verbose_name='رقم الحساب')),
                ('balance', models.FloatField(default=0.0, verbose_name='رصيد')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomeTreasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('balance', models.FloatField(default=0.0, verbose_name='رصيد')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
