# Generated by Django 3.2.5 on 2021-12-14 14:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Treasury', '0003_auto_20211214_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTreasuryTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(blank=True, max_length=255, null=True, verbose_name='عملية')),
                ('transaction_type', models.IntegerField(choices=[(1, 'داخل للخزنة'), (2, 'خارج من الخزنة')], default=0, verbose_name='نوع العملية')),
                ('value', models.FloatField(default=0.0, verbose_name='القيمة')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Treasury.worktreasury', verbose_name='الخزنة')),
            ],
        ),
        migrations.CreateModel(
            name='HomeTreasuryTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(blank=True, max_length=255, null=True, verbose_name='عملية')),
                ('transaction_type', models.IntegerField(choices=[(1, 'داخل للخزنة'), (2, 'خارج من الخزنة')], default=0, verbose_name='نوع العملية')),
                ('value', models.FloatField(default=0.0, verbose_name='القيمة')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Treasury.hometreasury', verbose_name='الخزنة')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(blank=True, max_length=255, null=True, verbose_name='عملية')),
                ('transaction_type', models.IntegerField(choices=[(1, 'داخل للخزنة'), (2, 'خارج من الخزنة')], default=0, verbose_name='نوع العملية')),
                ('value', models.FloatField(default=0.0, verbose_name='القيمة')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Treasury.bankaccount', verbose_name='الحساب')),
            ],
        ),
    ]
