# Generated by Django 3.2.5 on 2022-01-21 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المصنع')),
                ('hour_price', models.IntegerField(blank=True, null=True, verbose_name='حساب الساعه')),
                ('machine_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المكنة')),
                ('machine_count', models.IntegerField(null=True, verbose_name='عدد المكن')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='رقم الموبيل')),
                ('active', models.BooleanField(default=True, verbose_name='يعمل')),
                ('start_date', models.DateField(null=True, verbose_name='تاريخ البداية')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اضيف بواسطة')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('price', models.IntegerField(verbose_name='المبلغ')),
                ('recipient', models.CharField(max_length=50, verbose_name='المستلم')),
                ('admin', models.CharField(max_length=50, verbose_name='المسئول')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Factories.factory', verbose_name='المصنع')),
            ],
        ),
    ]
