# Generated by Django 3.2.5 on 2022-02-03 15:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المصنع')),
                ('hour_price', models.IntegerField(blank=True, null=True, verbose_name='حساب الساعه')),
                ('machine_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المكنة')),
                ('machine_count', models.IntegerField(null=True, verbose_name='عدد المكن')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='رقم الموبيل')),
                ('active', models.BooleanField(default=True, verbose_name='يعمل')),
                ('start_date', models.DateField(default=datetime.date.today, null=True, verbose_name='تاريخ البداية')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('price', models.IntegerField(verbose_name='المبلغ')),
                ('recipient', models.CharField(max_length=50, verbose_name='المستلم')),
                ('date', models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ')),
                ('admin', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Factories.factory', verbose_name='المصنع')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryOutSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('date', models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='الوزن جرام')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون')),
                ('percent_loss', models.FloatField(blank=True, null=True, verbose_name='نسبة الهالك')),
                ('weight_after_loss', models.FloatField(blank=True, null=True, verbose_name='الوزن بعد نسبة الهالك')),
                ('admin', models.CharField(blank=True, max_length=50, null=True, verbose_name='المسئول')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Factories.factory', verbose_name='المصنع')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryInSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('date', models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون')),
                ('product', models.CharField(max_length=50, verbose_name='الموديل')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name=' الوزن المستلم جرام')),
                ('product_weight', models.FloatField(blank=True, null=True, verbose_name='وزن القطعة جرام')),
                ('product_time', models.FloatField(blank=True, null=True, verbose_name='زمن القطعة دقائق')),
                ('product_count', models.FloatField(blank=True, null=True, verbose_name='عدد القطع')),
                ('hour_count', models.FloatField(blank=True, null=True, verbose_name='عدد الساعات')),
                ('hour_price', models.FloatField(blank=True, null=True, verbose_name='سعر الساعة')),
                ('total_account', models.FloatField(blank=True, null=True, verbose_name='اجمالي الحساب جنية')),
                ('admin', models.CharField(blank=True, max_length=50, null=True, verbose_name='المسئول')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Factories.factory', verbose_name='المصنع')),
            ],
        ),
    ]
