# Generated by Django 3.2.5 on 2022-02-20 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20220220_1721'),
        ('Factories', '0002_auto_20220219_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryinside',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product', verbose_name='الموديل'),
        ),
    ]
