# Generated by Django 3.2.5 on 2022-01-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0002_factory_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='created_by',
        ),
    ]
