# Generated by Django 3.2.5 on 2022-02-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0003_alter_factoryinside_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryinside',
            name='product_type',
            field=models.IntegerField(blank=True, choices=[(1, 'صدر'), (2, 'ضهر'), (3, 'كم'), (4, 'لياقة')], null=True, verbose_name='نوع القطع'),
        ),
        migrations.AddField(
            model_name='factoryinside',
            name='wool_type',
            field=models.IntegerField(blank=True, choices=[(1, 'قطن'), (2, 'صوف'), (3, 'لكرة'), (4, 'رمش'), (5, 'سبن'), (6, 'عصب'), (7, 'بلستر'), (7, 'استك')], null=True, verbose_name='نوع الخامة'),
        ),
        migrations.AddField(
            model_name='factoryoutside',
            name='wool_type',
            field=models.IntegerField(blank=True, choices=[(1, 'قطن'), (2, 'صوف'), (3, 'لكرة'), (4, 'رمش'), (5, 'سبن'), (6, 'عصب'), (7, 'بلستر'), (7, 'استك')], null=True, verbose_name='نوع الخامة'),
        ),
        migrations.AlterField(
            model_name='factoryinside',
            name='product_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='وزن القطعة بالجرام'),
        ),
        migrations.AlterField(
            model_name='factoryinside',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name=' الوزن المستلم بالكيلو'),
        ),
        migrations.AlterField(
            model_name='factoryoutside',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='الوزن بالكيلو'),
        ),
    ]
