# Generated by Django 3.2.5 on 2022-02-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0003_alter_factoryinside_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryinside',
            name='product_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='وزن القطعة بالجرام'),
        ),
        migrations.AlterField(
            model_name='factoryinside',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name=' الوزن المستلم بالكيلو'),
        ),
        migrations.AlterField(
            model_name='factoryoutside',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='الوزن بالكيلو'),
        ),
    ]
