# Generated by Django 3.2.5 on 2022-01-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0004_factoryoutside'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoryoutside',
            name='product',
        ),
        migrations.AlterField(
            model_name='factoryoutside',
            name='percent_loss',
            field=models.FloatField(blank=True, default=2, null=True, verbose_name='نسبة الهالك'),
        ),
    ]
