# Generated by Django 3.2.5 on 2022-01-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0005_auto_20220125_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryoutside',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='الرقم'),
        ),
    ]
