# Generated by Django 3.2.5 on 2022-01-25 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0006_alter_factoryoutside_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryInSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('date', models.DateField(null=True, verbose_name='التاريخ')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='الوزن')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون')),
                ('product', models.CharField(max_length=50, verbose_name='الموديل')),
                ('hour_price', models.FloatField(blank=True, null=True, verbose_name='سعر الساعة')),
                ('admin', models.CharField(blank=True, max_length=50, null=True, verbose_name='المسئول')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Factories.factory', verbose_name='المصنع')),
            ],
        ),
    ]
