# Generated by Django 3.2.5 on 2022-01-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0007_factoryinside'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryinside',
            name='hour_count',
            field=models.FloatField(blank=True, null=True, verbose_name='عدد الساعات'),
        ),
        migrations.AddField(
            model_name='factoryinside',
            name='product_number',
            field=models.FloatField(blank=True, null=True, verbose_name='عدد القطع'),
        ),
        migrations.AddField(
            model_name='factoryinside',
            name='product_time',
            field=models.FloatField(blank=True, null=True, verbose_name='زمن القطعة'),
        ),
        migrations.AddField(
            model_name='factoryinside',
            name='product_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='وزن القطعة'),
        ),
        migrations.AddField(
            model_name='factoryinside',
            name='total_account',
            field=models.FloatField(blank=True, null=True, verbose_name='اجمالي الحساب'),
        ),
        migrations.AlterField(
            model_name='factoryinside',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='الوزن المستلم'),
        ),
    ]
