# Generated by Django 3.2.5 on 2022-01-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0008_auto_20220126_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factoryinside',
            old_name='product_number',
            new_name='product_count',
        ),
    ]
