# Generated by Django 3.2.5 on 2022-01-27 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Factories', '0009_rename_product_number_factoryinside_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryinside',
            name='product_time',
            field=models.FloatField(blank=True, null=True, verbose_name='زمن القطعة دقائق'),
        ),
        migrations.AlterField(
            model_name='factoryinside',
            name='product_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='وزن القطعة جرام'),
        ),
        migrations.AlterField(
            model_name='factoryinside',
            name='total_account',
            field=models.FloatField(blank=True, null=True, verbose_name='اجمالي الحساب جنية'),
        ),
        migrations.AlterField(
            model_name='factoryinside',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name=' الوزن المستلم جرام'),
        ),
        migrations.AlterField(
            model_name='factoryoutside',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='الوزن جرام'),
        ),
       
    ]
