# Generated by Django 3.2.5 on 2022-01-27 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0010_auto_20220127_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryoutside',
            name='date',
            field=models.DateField(default=datetime.datetime.today, null=True, verbose_name='التاريخ'),
        ),
    ]
