# Generated by Django 3.2.5 on 2022-01-27 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0011_alter_factoryoutside_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryoutside',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ'),
        ),
    ]
