# Generated by Django 3.2.5 on 2022-01-27 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0012_alter_factoryoutside_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='start_date',
        ),
        migrations.AddField(
            model_name='factory',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='تاريخ البداية'),
        ),
        migrations.AlterField(
            model_name='factoryinside',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ'),
        ),
    ]
