# Generated by Django 3.2.5 on 2022-01-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0013_auto_20220127_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factory',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='factoryoutside',
            name='percent_loss',
            field=models.FloatField(blank=True, null=True, verbose_name='نسبة الهالك'),
        ),
    ]
