# Generated by Django 3.2.5 on 2022-02-03 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Factories', '0014_auto_20220127_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='admin',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول'),
        ),
    ]
