# Generated by Django 3.2.5 on 2022-02-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0015_alter_payment_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoryoutside',
            name='number',
        ),
    ]
