# Generated by Django 3.2.5 on 2022-03-06 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ السحب')),
                ('price', models.FloatField(verbose_name='المبلغ')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workers.worker', verbose_name=' العامل')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الحضور')),
                ('hour_count', models.IntegerField(choices=[(1, '6'), (2, '8'), (3, '12'), (4, '18')], default='12', verbose_name='العامل')),
                ('attend', models.BooleanField(default=0, verbose_name='حضر')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workers.worker', verbose_name='العامل')),
            ],
        ),
    ]
