# Generated by Django 3.2.5 on 2022-01-21 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم اللون')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الموديل')),
                ('code', models.CharField(max_length=50, null=True, verbose_name='كود الموديل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='صورة الموديل')),
                ('weight', models.CharField(blank=True, max_length=15, null=True, verbose_name='وزن الموديل')),
                ('cost', models.CharField(blank=True, max_length=15, null=True, verbose_name='التكلفة')),
                ('price', models.CharField(blank=True, max_length=15, null=True, verbose_name='سعر البيع')),
                ('size', models.CharField(max_length=10, verbose_name='المقاس')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.color', verbose_name='اللون')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اضيف بواسطة')),
            ],
        ),
    ]
