# Generated by Django 3.2.5 on 2022-02-19 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.AddField(
            model_name='color',
            name='code',
            field=models.CharField(default=1, max_length=20, verbose_name='كود اللون'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'شبابي'), (2, 'حريمي'), (3, 'اولاادي')], default=0, verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='كود الموديل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.color', verbose_name='اللون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (3, 'XL'), (3, 'XXL')], default=0, verbose_name='المقاس'),
        ),
    ]
