# Generated by Django 3.2.5 on 2022-03-08 21:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_remove_productwarehousetransactions_price_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='اسم التاجر')),
                ('phone', models.CharField(max_length=11, verbose_name='رقم الهاتف')),
                ('initial_balance_debit', models.FloatField(default=0, verbose_name='الدين الافتتاحي')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
            ],
        ),
        migrations.CreateModel(
            name='SellerPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_value', models.FloatField(default=0.0, verbose_name='القيمة المدفوعة')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 3, 8, 23, 20, 7, 661765), verbose_name='التاريخ')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productsellers', verbose_name='التاجر')),
            ],
        ),
        migrations.RemoveField(
            model_name='productwarehousetransactions',
            name='item',
        ),
        migrations.RemoveField(
            model_name='productwarehousetransactions',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='ProductWarehouses',
        ),
        migrations.DeleteModel(
            name='ProductWarehouseTransactions',
        ),
    ]
